#!/usr/bin/env bash
# scripts/dogfood_wss_tls.sh
#
# Prove wss:// + per-agent user credentials + CA trust for a remote adapter,
# with hub-server and hub-delegate on the user/password TCP listener.
#
# (Iteration-2 T1 rewrote this script: it used to prove a shared token. The
# hub now binds identity to credentials, so every participant connects as its
# own users[] entry generated by `hub-admin render-config`; the adapter's
# credential is restricted to the WebSocket listener.)
#
# Topology:
#   nats-server
#     TCP :users auth        (hub-server + hub-delegate, NATS_USER/NATS_PASSWORD)
#     WS  :TLS + users auth  (adapter: wss:// + --user/--password + --ca-file)
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${REPO_ROOT}/target}"
export PATH="${REPO_ROOT}/.tools/bin:${PATH}"
HUB_SERVER_BIN="${HUB_SERVER_BIN:-${CARGO_TARGET_DIR}/debug/hub-server}"
HUB_DELEGATE_BIN="${HUB_DELEGATE_BIN:-${CARGO_TARGET_DIR}/debug/hub-delegate}"
HUB_ADMIN_BIN="${HUB_ADMIN_BIN:-${CARGO_TARGET_DIR}/debug/hub-admin}"
PYTHON_BIN="${PYTHON_BIN:-${REPO_ROOT}/.venv/bin/python3}"
ADAPTER_SCRIPT="${REPO_ROOT}/remote_agent_adapter.py"
NATS_SERVER_BIN="${NATS_SERVER_BIN:-nats-server}"
CERT="${REPO_ROOT}/config/tls-example/nats-server.crt"
KEY="${REPO_ROOT}/config/tls-example/nats-server.key"

# Fixed dogfood credentials (loopback fixtures, NOT real secrets).
PW_REMOTE="dogfood-pw-wss-remote"
PW_BOSS="dogfood-pw-wss-boss"
PW_HUB="dogfood-pw-wss-hubserver"

TCP_PORT="${TCP_PORT:-14232}"
WS_PORT="${WS_PORT:-18090}"
HTTP_PORT="${HTTP_PORT:-18232}"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/nats-dogfood-wss-XXXXXX")"
CONF_PATH="${TMP_DIR}/nats.conf"
AGENTS_PATH="${TMP_DIR}/agents.txt"
LOG_DIR="${TMP_DIR}/logs"
mkdir -p "${LOG_DIR}"

CHILD_PIDS=()
cleanup() {
    local code=$?
    echo "--- cleanup (exit=${code}) ---"
    for pid in "${CHILD_PIDS[@]:-}"; do
        [[ -z "${pid:-}" ]] && continue
        kill "${pid}" 2>/dev/null || true
    done
    sleep 0.4
    for pid in "${CHILD_PIDS[@]:-}"; do
        [[ -z "${pid:-}" ]] && continue
        kill -9 "${pid}" 2>/dev/null || true
    done
    pkill -f "nats-server.*${TMP_DIR}" 2>/dev/null || true
    pkill -f "remote_agent_adapter.*dogfood-wss" 2>/dev/null || true
    pkill -f "hub-server.*${TMP_DIR}" 2>/dev/null || true
    rm -rf "${TMP_DIR}" 2>/dev/null || true
}
trap cleanup EXIT

die() { echo "FAIL: $*" >&2; exit 1; }
need() { [[ -x "$1" ]] || [[ -f "$1" ]] || die "missing $1"; }

need "${HUB_SERVER_BIN}"
need "${HUB_DELEGATE_BIN}"
need "${HUB_ADMIN_BIN}"
need "${ADAPTER_SCRIPT}"
need "${CERT}"
need "${KEY}"
command -v "${NATS_SERVER_BIN}" >/dev/null || die "nats-server not on PATH"
[[ -x "${PYTHON_BIN}" ]] || die "python not executable: ${PYTHON_BIN}"

CERT_ABS="$(cd "$(dirname "${CERT}")" && pwd)/$(basename "${CERT}")"
KEY_ABS="$(cd "$(dirname "${KEY}")" && pwd)/$(basename "${KEY}")"

# ── 1. Agents file → hub-admin render-config (WS TLS) ───────────────
cat > "${AGENTS_PATH}" <<EOF
# <id> <role> <secret> [ws-only] [channels...]
dogfood-wss   worker        pw:${PW_REMOTE}   ws-only
dogfood-boss  orchestrator  pw:${PW_BOSS}
EOF
"${HUB_ADMIN_BIN}" render-config \
    --agents "${AGENTS_PATH}" \
    --port "${TCP_PORT}" \
    --ws-port "${WS_PORT}" \
    --tls-cert "${CERT_ABS}" \
    --tls-key "${KEY_ABS}" \
    --hub-password "${PW_HUB}" \
    --out "${CONF_PATH}" || die "render-config failed"
echo "http_port: ${HTTP_PORT}" >> "${CONF_PATH}"
echo "[conf] rendered ${CONF_PATH} via hub-admin"
"${NATS_SERVER_BIN}" -t -c "${CONF_PATH}" || die "nats-server -t failed"

echo "=== dogfood: wss:// + per-agent users + CA (full-stack auth) ==="
echo "TMP_DIR=${TMP_DIR}  TCP=${TCP_PORT} (users)  WS=${WS_PORT} (TLS+users)"

"${NATS_SERVER_BIN}" -c "${CONF_PATH}" >"${LOG_DIR}/nats.stdout" 2>&1 &
CHILD_PIDS+=("$!")
echo "[start] nats-server pid=${CHILD_PIDS[-1]}"

for i in $(seq 1 30); do
    ss -ltn 2>/dev/null | grep -q ":${TCP_PORT} " && { echo "[wait] TCP up"; break; }
    sleep 0.2
    [[ $i -eq 30 ]] && die "nats TCP never listened"
done
for i in $(seq 1 30); do
    ss -ltn 2>/dev/null | grep -q ":${WS_PORT} " && { echo "[wait] WS up"; break; }
    sleep 0.2
    [[ $i -eq 30 ]] && die "nats WS never listened"
done

# ── 2. Negative controls ────────────────────────────────────────────
echo "=== negative: wss without credentials must fail ==="
if "${PYTHON_BIN}" - <<PY 2>"${LOG_DIR}/neg.err"
import asyncio, ssl, nats
async def main():
    ctx = ssl.create_default_context(cafile="${CERT_ABS}")
    await nats.connect(servers=["wss://127.0.0.1:${WS_PORT}"], tls=ctx, connect_timeout=3)
asyncio.run(main())
print("UNEXPECTED_OK")
PY
then
    die "credential-less wss connect unexpectedly succeeded"
fi
grep -qiE "Authorization|auth|permissions|timeout|Error" "${LOG_DIR}/neg.err" || {
    cat "${LOG_DIR}/neg.err" >&2
    die "expected auth error on credential-less connect"
}
echo "[neg1] PASS — wss without credentials rejected"

echo "=== negative: wss with wrong password must fail ==="
if "${PYTHON_BIN}" - <<PY 2>"${LOG_DIR}/neg2.err"
import asyncio, ssl, nats
async def main():
    ctx = ssl.create_default_context(cafile="${CERT_ABS}")
    await nats.connect(servers=["wss://127.0.0.1:${WS_PORT}"], tls=ctx,
                       user="dogfood-wss", password="wrong-password",
                       connect_timeout=3)
asyncio.run(main())
print("UNEXPECTED_OK")
PY
then
    die "wrong-password wss connect unexpectedly succeeded"
fi
echo "[neg2] PASS — wss with wrong password rejected"

# ── 3. hub-server + adapter + delegate round-trip ───────────────────
NATS_USER=hub-server NATS_PASSWORD="${PW_HUB}" \
"${HUB_SERVER_BIN}" --nats-url "nats://127.0.0.1:${TCP_PORT}" \
    --require-bound-identity \
    >"${LOG_DIR}/hub-server.log" 2>&1 &
CHILD_PIDS+=("$!")
sleep 1
kill -0 "${CHILD_PIDS[-1]}" 2>/dev/null || {
    cat "${LOG_DIR}/hub-server.log" >&2
    die "hub-server exited early"
}
echo "[start] hub-server pid=${CHILD_PIDS[-1]} (user=hub-server, require-bound)"

PYTHONUNBUFFERED=1 "${PYTHON_BIN}" -u "${ADAPTER_SCRIPT}" \
    --identity dogfood-wss \
    --nats-url "wss://127.0.0.1:${WS_PORT}" \
    --user dogfood-wss \
    --password "${PW_REMOTE}" \
    --ca-file "${CERT_ABS}" \
    --backend shell \
    --execute echo \
    >"${LOG_DIR}/adapter.log" 2>&1 &
CHILD_PIDS+=("$!")
echo "[start] adapter pid=${CHILD_PIDS[-1]} (wss + user + ca)"

for i in $(seq 1 40); do
    if grep -q "connected to NATS as dogfood-wss" "${LOG_DIR}/adapter.log" 2>/dev/null; then
        echo "[wait] adapter connected (${i} checks)"
        break
    fi
    sleep 0.25
    [[ $i -eq 40 ]] && {
        cat "${LOG_DIR}/adapter.log" >&2
        die "adapter never connected"
    }
done

echo "=== round-trip hub-delegate → dogfood-wss ==="
set +e
DELEGATE_OUT="$(NATS_USER=dogfood-boss NATS_PASSWORD="${PW_BOSS}" \
"${HUB_DELEGATE_BIN}" \
    --nats-url "nats://127.0.0.1:${TCP_PORT}" \
    --to dogfood-wss \
    --from dogfood-boss \
    --prompt "ping-w3c-wss" \
    --timeout 30 \
    --verbose 2>&1)"
DELEGATE_RC=$?
set -e
echo "--- delegate output ---"
echo "${DELEGATE_OUT}"
echo "--- end ---"

[[ ${DELEGATE_RC} -eq 0 ]] || die "hub-delegate exit=${DELEGATE_RC}"
echo "${DELEGATE_OUT}" | grep -q "ping-w3c-wss" || die "echo payload missing"
echo "${DELEGATE_OUT}" | grep -qi "completed" || die "completed event missing"

echo
echo "==================== PASS ===================="
exit 0
