#!/usr/bin/env bash
# scripts/dogfood_token_auth.sh
#
# Local dogfood: per-agent user credentials + identity-bound subjects +
# WebSocket remote adapter round-trip.
#
# (Iteration-2 T1 rewrote this script: it used to prove token auth on the WS
# listener. The hub now binds identity to credentials, so every participant —
# hub-server, hub-delegate, remote adapter — connects as its own users[] entry
# generated by `hub-admin render-config`; the adapter's credential is restricted
# to the WebSocket listener via allowed_connection_types.)
#
# Topology under test:
#
#   ┌─────────────────────────── nats-server ───────────────────────────┐
#   │  TCP listener 14222  (users auth; hub-server + hub-delegate)      │
#   │  WS  listener 18080  (users auth; adapter creds are WS-ONLY)      │
#   └──────┬──────────────┴─────────────────────────────────────────────┘
#          │                     │ ws://127.0.0.1:18080 --user/--password
#          │ nats://…userinfo    ↓
#   ┌──────┴──────┐         ┌──────────────────────┐
#   │ hub-server  │         │ remote_agent_adapter │   (Python)
#   │ (Rust)      │         │ identity=dogfood-    │
#   └──────┬──────┘         │   remote             │
#          │                │ backend=shell echo   │
#   ┌──────┴──────────┐     └──────────────────────┘
#   │ hub-delegate    │  sends one-shot prompt "ping-wave2e"
#   │ (dogfood-boss)  │  to dogfood-remote via hub.pub.boss.task.<uuid>
#   └─────────────────┘
#
# Security claims proven by this run:
#   - The server rejects every connection that presents no credentials, and
#     rejects a valid user with a wrong password (negative controls).
#   - The adapter's credential is WebSocket-only: the same user/password is
#     REFUSED on the plain TCP listener.
#   - Every client publishes only on subjects bound to its own identity;
#     the round trip works under --require-bound-identity.
#
# Self-contained: writes temp dir + conf, starts everything, tears down on exit.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${REPO_ROOT}/target}"
export PATH="${REPO_ROOT}/.tools/bin:${PATH}"
HUB_SERVER_BIN="${HUB_SERVER_BIN:-${CARGO_TARGET_DIR}/debug/hub-server}"
HUB_DELEGATE_BIN="${HUB_DELEGATE_BIN:-${CARGO_TARGET_DIR}/debug/hub-delegate}"
HUB_ADMIN_BIN="${HUB_ADMIN_BIN:-${CARGO_TARGET_DIR}/debug/hub-admin}"
PYTHON_BIN="${PYTHON_BIN:-${REPO_ROOT}/.venv/bin/python3}"
ADAPTER_SCRIPT="${REPO_ROOT}/remote_agent_adapter.py"
NATS_SERVER_BIN="${NATS_SERVER_BIN:-nats-server}"

# Fixed dogfood credentials (NOT real secrets — loopback fixtures only).
PW_REMOTE="dogfood-pw-remote"
PW_BOSS="dogfood-pw-boss"
PW_HUB="dogfood-pw-hubserver"

TCP_PORT="${TCP_PORT:-14222}"
WS_PORT="${WS_PORT:-18080}"
HTTP_PORT="${HTTP_PORT:-18222}"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/nats-dogfood-XXXXXX")"
CONF_PATH="${TMP_DIR}/nats.conf"
AGENTS_PATH="${TMP_DIR}/agents.txt"
DB_PATH="${TMP_DIR}/db"
LOG_DIR="${TMP_DIR}/logs"
mkdir -p "${LOG_DIR}" "${DB_PATH}"

CHILD_PIDS=()
cleanup() {
    local code=$?
    echo "--- cleanup (exit=${code}) ---"
    for pid in "${CHILD_PIDS[@]:-}"; do
        [[ -z "${pid:-}" ]] && continue
        kill "${pid}" 2>/dev/null || true
    done
    sleep 0.5
    for pid in "${CHILD_PIDS[@]:-}"; do
        [[ -z "${pid:-}" ]] && continue
        kill -9 "${pid}" 2>/dev/null || true
    done
    pkill -f "nats-server.*${TMP_DIR}" 2>/dev/null || true
    pkill -f "remote_agent_adapter.*dogfood-remote" 2>/dev/null || true
    pkill -f "hub-server.*${TMP_DIR}" 2>/dev/null || true
    rm -rf "${TMP_DIR}" 2>/dev/null || true
}
trap cleanup EXIT

wait_for_port() {
    local port="$1" label="$2" max="${3:-15}"
    local tries=0
    while (( tries < max )); do
        if (echo > "/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
            echo "[wait] ${label} on ${port} listening (after ${tries}s)"
            return 0
        fi
        tries=$((tries + 1))
        sleep 1
    done
    echo "[wait] TIMEOUT waiting for ${label} on ${port}" >&2
    return 1
}

echo "=== dogfood: per-agent users + WS remote adapter round-trip ==="
echo "TMP_DIR=${TMP_DIR}"
echo "TCP_PORT=${TCP_PORT} (users auth)  WS_PORT=${WS_PORT} (users auth, adapter creds WS-only)"

for bin in "${HUB_SERVER_BIN}" "${HUB_DELEGATE_BIN}" "${HUB_ADMIN_BIN}" "${ADAPTER_SCRIPT}"; do
    [[ -e "${bin}" ]] || { echo "PREFLIGHT FAIL: missing ${bin}" >&2; exit 2; }
done
command -v "${NATS_SERVER_BIN}" >/dev/null 2>&1 || { echo "PREFLIGHT FAIL: nats-server not on PATH" >&2; exit 2; }
[[ -x "${PYTHON_BIN}" ]] || { echo "PREFLIGHT FAIL: python not executable at ${PYTHON_BIN}" >&2; exit 2; }

# ── 1. Agents file → hub-admin render-config → nats.conf ────────────
# dogfood-remote is ws-only: its credential is refused on the TCP listener.
cat > "${AGENTS_PATH}" <<EOF
# <id> <role> <secret> [ws-only] [channels...]
dogfood-remote   worker        pw:${PW_REMOTE}   ws-only
dogfood-boss     orchestrator  pw:${PW_BOSS}
EOF
"${HUB_ADMIN_BIN}" render-config \
    --agents "${AGENTS_PATH}" \
    --port "${TCP_PORT}" \
    --ws-port "${WS_PORT}" \
    --hub-password "${PW_HUB}" \
    --out "${CONF_PATH}" || { echo "PREFLIGHT FAIL: render-config" >&2; exit 2; }
# monitoring port is not part of render-config output
echo "http_port: ${HTTP_PORT}" >> "${CONF_PATH}"
echo "[conf] rendered ${CONF_PATH} via hub-admin"
"${NATS_SERVER_BIN}" -t -c "${CONF_PATH}" || { echo "PREFLIGHT FAIL: nats-server -t" >&2; exit 2; }

# ── 2. Start nats-server ────────────────────────────────────────────
"${NATS_SERVER_BIN}" -c "${CONF_PATH}" > "${LOG_DIR}/nats.log" 2>&1 &
CHILD_PIDS+=("$!")
echo "[start] nats-server pid=$!"
wait_for_port "${TCP_PORT}" "nats-server(TCP)" 15 || exit 3
wait_for_port "${WS_PORT}"  "nats-server(WS)"  15 || exit 3

# ── 3. NEGATIVE CONTROLS ────────────────────────────────────────────
echo "=== negative controls ==="
NEG_PROBE="${TMP_DIR}/neg_probe.py"
cat > "${NEG_PROBE}" <<'PY'
import asyncio, sys, nats
async def main():
    url = sys.argv[1]
    user = sys.argv[2] or None
    pw = sys.argv[3] or None
    try:
        nc = await nats.connect(url, user=user, password=pw,
                                name="neg-probe", allow_reconnect=False,
                                connect_timeout=4)
        print("UNEXPECTED: connected")
        await nc.close()
    except Exception as e:
        print(f"OK-rejected: {type(e).__name__}: {str(e)[:80]}")
asyncio.run(main())
PY

NEG_OUT=$("${PYTHON_BIN}" "${NEG_PROBE}" "ws://127.0.0.1:${WS_PORT}" "" "" 2>&1 | grep -v "Unclosed\|client_session")
echo "${NEG_OUT}"
echo "${NEG_OUT}" | grep -q "OK-rejected" \
    && echo "[neg1] PASS — WS without credentials is rejected" \
    || { echo "[neg1] FAIL" >&2; exit 7; }

NEG_OUT=$("${PYTHON_BIN}" "${NEG_PROBE}" "ws://127.0.0.1:${WS_PORT}" "dogfood-remote" "wrong-password" 2>&1 | grep -v "Unclosed\|client_session")
echo "${NEG_OUT}"
echo "${NEG_OUT}" | grep -q "OK-rejected" \
    && echo "[neg2] PASS — WS with wrong password is rejected" \
    || { echo "[neg2] FAIL" >&2; exit 7; }

# WS-only credential must be refused on the TCP listener.
NEG_OUT=$("${PYTHON_BIN}" "${NEG_PROBE}" "nats://127.0.0.1:${TCP_PORT}" "dogfood-remote" "${PW_REMOTE}" 2>&1 | grep -v "Unclosed\|client_session")
echo "${NEG_OUT}"
echo "${NEG_OUT}" | grep -q "OK-rejected" \
    && echo "[neg3] PASS — WS-only credential refused on TCP listener" \
    || { echo "[neg3] FAIL" >&2; exit 7; }

# ── 4. Start hub-server (TCP, bound-identity mode) ──────────────────
NATS_USER=hub-server NATS_PASSWORD="${PW_HUB}" \
"${HUB_SERVER_BIN}" \
    --nats-url "nats://127.0.0.1:${TCP_PORT}" \
    --db-path "" \
    --require-bound-identity \
    > "${LOG_DIR}/hub-server.log" 2>&1 &
HUB_PID=$!
CHILD_PIDS+=("${HUB_PID}")
echo "[start] hub-server pid=${HUB_PID} (user=hub-server, require-bound)"
sleep 2
kill -0 "${HUB_PID}" 2>/dev/null || {
    echo "FAIL: hub-server exited early. Tail:" >&2
    tail -30 "${LOG_DIR}/hub-server.log" >&2
    exit 4
}

# ── 5. Start remote_agent_adapter (ws:// + per-agent user) ──────────
PYTHONPATH="${REPO_ROOT}:${PYTHONPATH:-}" \
PYTHONUNBUFFERED=1 \
"${PYTHON_BIN}" -u "${ADAPTER_SCRIPT}" \
    --identity dogfood-remote \
    --nats-url "ws://127.0.0.1:${WS_PORT}" \
    --user dogfood-remote \
    --password "${PW_REMOTE}" \
    --backend shell \
    --execute "echo" \
    > "${LOG_DIR}/adapter.log" 2>&1 &
ADAPTER_PID=$!
CHILD_PIDS+=("${ADAPTER_PID}")
echo "[start] remote_agent_adapter pid=${ADAPTER_PID} (ws + user dogfood-remote)"
for i in $(seq 1 25); do
    if grep -q "connected to NATS as dogfood-remote" "${LOG_DIR}/adapter.log" 2>/dev/null; then
        echo "[wait] adapter connected after ${i}s"
        break
    fi
    sleep 1
done
grep -q "connected to NATS as dogfood-remote" "${LOG_DIR}/adapter.log" 2>/dev/null || {
    echo "FAIL: adapter did not connect within 25s. Tail:" >&2
    tail -40 "${LOG_DIR}/adapter.log" >&2
    exit 5
}
kill -0 "${ADAPTER_PID}" 2>/dev/null || {
    echo "FAIL: adapter exited after connecting. Tail:" >&2
    tail -40 "${LOG_DIR}/adapter.log" >&2
    exit 6
}

# ── 6. hub-delegate one-shot prompt ─────────────────────────────────
echo "=== round-trip: hub-delegate --to dogfood-remote --prompt ping-wave2e ==="
DELEGATE_OUT="${LOG_DIR}/delegate.out"
set +e
NATS_USER=dogfood-boss NATS_PASSWORD="${PW_BOSS}" \
"${HUB_DELEGATE_BIN}" \
    --nats-url "nats://127.0.0.1:${TCP_PORT}" \
    --to dogfood-remote \
    --from dogfood-boss \
    --prompt "ping-wave2e" \
    --timeout 30 \
    --verbose > "${DELEGATE_OUT}" 2>&1
DELEGATE_RC=$?
set -e
echo "[delegate] exit=${DELEGATE_RC}"
echo "--- delegate output ---"
cat "${DELEGATE_OUT}"
echo "--- end delegate output ---"

# ── 7. Verdict ──────────────────────────────────────────────────────
PASS=1
[[ "${DELEGATE_RC}" -eq 0 ]] || { echo "FAIL: hub-delegate exited ${DELEGATE_RC}" >&2; PASS=0; }
if ! grep -qE "(ping-wave2e|done|completed|reply|✓|RESULT)" "${DELEGATE_OUT}" 2>/dev/null; then
    if [[ "${DELEGATE_RC}" -eq 0 && -s "${DELEGATE_OUT}" ]]; then
        echo "[warn] delegate exit=0 but no obvious echo signal; treating as pass per exit code"
    else
        echo "FAIL: no echo/done signal in delegate output" >&2
        PASS=0
    fi
fi

echo
echo "=== adapter.log tail (evidence) ==="
tail -25 "${LOG_DIR}/adapter.log" || true
echo
echo "=== nats.log tail (evidence) ==="
tail -15 "${LOG_DIR}/nats.log" || true
echo
echo "=== hub-server.log tail (evidence) ==="
tail -15 "${LOG_DIR}/hub-server.log" || true

if [[ "${PASS}" -eq 1 ]]; then
    echo
    echo "==================== PASS ===================="
    exit 0
else
    echo
    echo "==================== FAIL ===================="
    exit 1
fi
